### ISSUE TITLE
Example App Logged User

### ISSUE THREAD

**Issue by myaicreator** [fa0311/twitter_openapi_dart#3]
Hi I tested and all features work great on ios. But I could not find how to access the profile information of the logged in user.
Can you please add profile page.

**Comment by fa0311** [comment]
Logged-in users cannot be retrieved by the GraphQL API, so we implemented our own without using twitter_openapi_dart_generated.
This requires TwitterInitialStateDart.

```dart
TwitterInitialStateDart.fromCookies(ct0 : "<ct0 here>", authToken : "<ct0 here>");
```
Or you can create one from TwitterOpenapiDart.

```dart
TwitterOpenapiDart.fromCookies(ct0 : "<ct0 here>", authToken : "<ct0 here>").getTwitterInitialStateDart();
```

However, please note the following.
```dart
final client = TwitterOpenapiDart.fromCookies(ct0: "", authToken: "");
final clientInitialState = client.getTwitterInitialStateDart();

print(client.dio == clientInitialState.dio); // false
print(client.dio.options == clientInitialState.dio.options); // true
print(client.dio.interceptors == clientInitialState.dio.interceptors); // false
```

The implementation is as follows.
<https://github.com/fa0311/twitter_openapi_dart/blob/4123b15d3f02a3ff7a05f5bcf81f8f889cec735f/twitter_openapi_dart/lib/src/api.dart#L73-L80>


This is sample code.
```dart
final clientInitialState = client.getTwitterInitialStateDart();
final result = await client.getInitialStateApi().getHome();
if (result.session == null) {
  print("You are not logged in");
} else {
  print("Your name is ${result.session!.screenName}");
}
````

**Comment by myaicreator** [comment]
Hello, we are sending userId value in all APIs. When I tried the codes you
gave above, I noticed that the userId value of the user was not returned.
How can we use a code to list the followers/followings of the logged in
user. And instead of going to the login screen every time we restart the
app, it might be better to check the cookies and send them to the login
screen if logged out. Thanks.

ふぁ ***@***.***>, 26 Nis 2023 Çar, 04:01 tarihinde şunu yazdı:

**Comment by fa0311** [comment]
```dart
final api = TwitterOpenapiDart();
final client = await api.getClientFromCookies(ct0: "<ct0 here>", authToken: "<ct0 here>");
final result = await client.getInitialStateApi().getHome();
final userId = result.session!.userId;
final followers = await client.getUserListApi().getFollowers(userId: userId);
followers.data.map((e) => e.user.legacy.screenName).forEach(print);
```

**Comment by fa0311** [comment]
> And instead of going to the login screen every time we restart the app, it might be better to check the cookies

Required to maintain login as Token Refresh is not implemented.
